# Generated by Django 2.2.2 on 2019-11-03 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('article', models.TextField(verbose_name='Short and Sweet article!')),
                ('slug', models.SlugField(max_length=255)),
                ('category', models.CharField(choices=[('0', 'Politics'), ('1', 'Technologies'), ('2', 'Sports'), ('3', 'Fashion')], max_length=2)),
                ('cover_image', models.ImageField(upload_to='uploads')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'newses',
            },
        ),
    ]
